### PR TITLE
Mind expiry date when looking for sig for subkey

### PR DESCRIPTION
**Pull request by zapu**
When parsing keys, take the signature with furthest expiration date,
instead of the first signature that comes along.

Fixes: https://github.com/keybase/keybase-issues/issues/2604
Internal ticket: CORE-3879

@oconnor663 Please review, thank you!

### CODE REVIEW

**Comment by zapu** [comment]
But can also wait for @maxtaco , no problem!

**Review by maxtaco — APPROVED** [review]

**Comment by maxtaco** [comment]
Great work! 👍

**Comment by smurfix** [comment]
Thanks a lot!
However: If the signature you find isn't even valid currently, you still have a problem.

**Comment by zapu** [comment]
I think the signatures are checked beforehand (`err = e.PrimaryKey.VerifyKeySignature(subKey.PublicKey, sig)`, line 594) so if it happens that there is a signature that extends further in time but is invalid, it will not "win".

**Comment by zapu** [comment]
Also thank you for your patience! It will probably take a few days before client's dependency is updated and a new version is released.

**Pull request merged**
