### PR TITLE
Fix rsa large exponent keys

### PR DESCRIPTION
**Pull request by zapu**
Add `crypto/rsa` fork back in to fix large exponent keys.

### CODE REVIEW

**Review by akalin-keybase — APPROVED** [review]
lgtm!

**Comment by maxtaco** [comment]
Any chance of upstreaming our patch?

**Review by maxtaco — APPROVED** [review]

**Comment by zapu** [comment]
They rejected it last time: https://github.com/golang/go/issues/17970 might be worth it to try again.

**Comment by maxtaco** [comment]
Ah, urg, ok. What about the other approach, which is to shitcan this key.  Does that break this guy's account?

**Comment by zapu** [comment]
It does, unfortunately. But we had this for years until I accidentally switched to importing `crypto/rsa` instead, so we are essentially just fixing the regression here. I think there may be more people in similar situation who hasn't reported it.

**Comment by maxtaco** [comment]
OK 👍

**Pull request merged**
